### ISSUE TITLE
NuGet Package Manager Not Using Latest Version

### ISSUE THREAD

**Issue by bchavez** [PrintsCharming/ObjectHydrator#7]
There might be something wrong with your nuget package definition.

I'm using a VS2013 project with .NET 4.5.1 and the only valid version is 0.6.0 of objecthydrator.

![screen408](https://cloud.githubusercontent.com/assets/478118/8013835/b52ed2c2-0b80-11e5-9d65-55b687d3cb1a.png)

I had to manually force the version with:

`Install-Package objecthydrator -Version 1.1.0`

**Comment by PrintsCharming** [comment]
For some reason the UI shows 0.6.0 but even if you left out the version number on the command line it would install 1.1.0
